main:
  - name: Syllabus
    url: /syllabus/
    weight: 2
  - name: Schedule
    url: /schedule/
    weight: 1
  - name: Resources
    url: /resource/
    weight: 3
  - name: Final Project
    url: /finalproject/
    weight: 4

resource:
  - name: Resources
    weight: 1
  - name: Guides
    weight: 2
