baseURL: "/"
languageCode: en-us
title: "Modern Research Methods:"
theme: "ath-tufte-hugo_archivo"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.Rhistory$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
  - \.Rproj.user/*
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: RStudio.cloud
      url: "https://rstudio.cloud"
      weight: 4
    - name: Resources
      url: /resources/
      weight: 3
params:
  subtitle: "Cumulative Science, Big Data, and Meta-Analysis"
  author: Molly Lewis
  thumbnail: /noun_Graph_963326.png
  instructor: 
    name:  Dr. Molly Lewis
    email: mollylewis@cmu.edu
    url: "http://www.andrew.cmu.edu/user/mollylew/"
    github: 
    office: Porter 223A
    oh: W 4:00-6:00pm
  ta: 
    name:  Jaeah Kim
    email: jaeahk@andrew.cmu.edu
    office: Baker 455E
    oh: M 1:00-3:00pm
  course:
    number: 85311
    semester: Spring 2020
    days: "MW (lecture); F (lab)"
    time: "10:30-11:50am"
    location1: "Lecture: Baker 336B"
    location2: "Lab: Baker 332P"
    dates: "January - May 2020"
    copyrightYear: "2019"
    contactDetails: >-
       
       
      
  university: 
    name: Carnegie Mellon University
    url: "https://www.cmu.edu"
  school:
    name: Department of Psychology
    url: ""
  description: ""
  primaryColor: "#E50000"
  secondaryColor: "#D08770"
  credits: "Image credits: icon created by Shastry from Noun Project; [cover photo](https://www.sciencefocus.com/science/how-to-build-the-perfect-human-pyramid/) "
  logo:
    url: /images/noun_Graph_963326.png
    alt: Cumulative Science Methods
  meta:
    twitterSite: ""
    twitterCreator: ""
    fbAuthor: ""
