baseURL: "/"
languageCode: en-us
title: "Modern Research Methods:"
theme: "ath-tufte-hugo_archivo"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.Rhistory$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
  - \.Rproj.user/*
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Resources
      url: /resources/
      weight: 3
    - name: Final Project
      url: /finalproject/
      weight: 4
params:
  subtitle: "Cumulative Science, Big Data, and Meta-Analysis"
  author: Molly Lewis
  thumbnail: /noun_Graph_963326.png
  instructor: 
    name:  Dr. Molly Lewis
    email: mollylewis@cmu.edu
    url: "http://www.andrew.cmu.edu/user/mollylew/"
    office: "Porter Hall 208H"
    oh: "W 3:00-5:00pm"
  ta: 
    name:  Roderick Seow 
    email: XXX
    office: "XXX"
    oh: XXXX
  course:
    number: 85311
    semester: Fall 2021
    days: "MW (lecture); F (lab)"
    time: "1:25-2:15pm"
    location1: "Mellon Institute 448"
    dates: "August - December 2021"
    copyrightYear: "2021"
    contactDetails: >-
       
       
      
  university: 
    name: Carnegie Mellon University
    url: "https://www.cmu.edu"
  school:
    name: Department of Psychology
    url: ""
  description: ""
  primaryColor: "#E50000"
  secondaryColor: "#D08770"
  credits: "Image credits: icon created by Shastry from Noun Project; [cover photo](https://www.sciencefocus.com/science/how-to-build-the-perfect-human-pyramid/) "
  logo:
    url: /images/noun_Graph_963326.png
    alt: Cumulative Science Methods
  meta:
    twitterSite: ""
    twitterCreator: ""
    fbAuthor: ""
