baseURL: "/"
languageCode: en-us
title: "Modern Research Methods:"
theme: "ath-tufte-hugo_archivo"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.Rhistory$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
  - \.Rproj.user/*
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: RStudio.cloud
      url: "https://rstudio.cloud"
      weight: 4
    - name: Resources
      url: /resources/
      weight: 3
    - name: Final Project
      url: /finalproject/
      weight: 5
params:
  subtitle: "Cumulative Science, Big Data, and Meta-Analysis"
  author: Molly Lewis
  thumbnail: /noun_Graph_963326.png
  instructor: 
    name:  Dr. Molly Lewis
    email: mollylewis@cmu.edu
    url: "http://www.andrew.cmu.edu/user/mollylew/"
    signup: "<b> [signup sheet](https://docs.google.com/spreadsheets/d/1gvTX55rFdZFoDbV0nyXaefbQKTvlDbTdqUfQJNxl4BQ/edit#gid=0)</b>"
    office: "<b> [ZOOM OFFICE](https://cmu.zoom.us/j/765835761) </b>"
    oh: "W 4:30-6:30pm"
  ta: 
    name:  Jaeah Kim
    email: jaeahk@andrew.cmu.edu
    signup: "<b> [signup sheet](https://docs.google.com/spreadsheets/d/1gvTX55rFdZFoDbV0nyXaefbQKTvlDbTdqUfQJNxl4BQ/edit#gid=0)</b>"
    office: "<b> [ZOOM OFFICE](https://cmu.zoom.us/j/538037017) </b>"
    oh: M 1:00-3:00pm 
  course:
    number: 85311
    semester: Spring 2020
    days: "MW (lecture); F (lab)"
    time: "10:30-11:20am"
    location1: "Lecture/Lab:  <b> [ZOOM CLASSROOM](https://cmu.zoom.us/j/602836260)</b>"
    dates: "January - May 2020"
    copyrightYear: "2019"
    contactDetails: >-
       
       
      
  university: 
    name: Carnegie Mellon University
    url: "https://www.cmu.edu"
  school:
    name: Department of Psychology
    url: ""
  description: ""
  primaryColor: "#E50000"
  secondaryColor: "#D08770"
  credits: "Image credits: icon created by Shastry from Noun Project; [cover photo](https://www.sciencefocus.com/science/how-to-build-the-perfect-human-pyramid/) "
  logo:
    url: /images/noun_Graph_963326.png
    alt: Cumulative Science Methods
  meta:
    twitterSite: ""
    twitterCreator: ""
    fbAuthor: ""
