baseURL: "/"
languageCode: en-us
title: "Modern Research Methods: Cumulative Science, Big Data, and Meta-Analysis"
theme: "ath-tufte-hugo_archivo"
googleAnalytics: ""
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - \.Rhistory$
  - \.yaml$
  - _files$
  - _cache$
  - \.csl$
  - \.Rproj.user/*
permalinks:
  post: "/:year/:month/:day/:slug/"
buildFuture: true
menu:
  main:
    - name: Syllabus
      url: /syllabus/
      weight: 1
    - name: Schedule
      url: /schedule/
      weight: 2
    - name: Assignments
      url: /assignments/
      weight: 3
params:
  author: Molly Lewis
  thumbnail: /noun_Graph_963326.png
  instructor: 
    name:  Dr. Molly Lewis
    email: mollylewis@cmu.edu
    url: "http://www.andrew.cmu.edu/user/mollylew/"
    github: 
    office: Porter Hall 223-A
  course:
    number: PSYCH 85-311
    semester: Spring 2020
    days: "MW; F (lab)"
    time: "XXX"
    location: "XXX"
    dates: "XXX"
    copyrightYear: "2019"
    contactDetails: >-
      Office hours: TBD
  university: 
    name: Carnegie Mellon University
    url: "https://www.cmu.edu"
  school:
    name: Department of Psychology
    url: ""
  description: ""
  primaryColor: "#E50000"
  secondaryColor: "#D08770"
  credits: "Image credits: icon created by Shastry from Noun Project; [cover photo](https://www.sciencefocus.com/science/how-to-build-the-perfect-human-pyramid/) "
  logo:
    url: /images/noun_Graph_963326.png
    alt: Cumulative Science Methods
  meta:
    twitterSite: ""
    twitterCreator: ""
    fbAuthor: ""
