---
title: "Assignments"
slug: assignments
---

All assignments will be linked on the [schedule page](/schedule/) page. 

# Lab Assignments

There will be 8 Lab Assignments throughout the semester. The goal of these assignments is to give you hands-on experience with the skills that are introduced in lecture and in lab. You are welcomed, and encouraged, to work with each other on the problems. But, you must turn in your own work.

Submission instructions: Always submit the .Rmd and .HTML files via XX.


# Midterm Exam

There will be a take-home midterm exam that will assess your conceptual understanding of the topics covered in the first part of the semester through short answer responses.


# Final project

The final project will be an original meta-analysis on a topic in cognitive or developmental psychology. You are encouraged to work on the project in groups of 1-3; however, each student must complete their own final write-up. Scope and topics of the meta-analysis will be  decided in consultation with me.

There is no final exam. This project is your final exam.
